

get http://localhost:3000/users
Content-Type: application/json

###

get http://localhost:3000/users/42
Content-Type: application/json

###

post http://localhost:3000/users/register
Content-Type: application/json

{
    "nom":"jihane",
    "email":"jihan@gmail.com",
    "password":"jihane123",
    "role":"AUTHOR"
}

###

post http://localhost:3000/users/login
Content-Type: application/json

{
    "email":"jihan@gmail.com",
    "password":"jihane123"
}

###

patch http://localhost:3000/users/1
Content-Type: application/json

{
    "nom":"jiji",
    "email":"jiji11@gmail.com",
    "password":"jiji1122",
    "role":"USER"
}


###

delete http://localhost:3000/users/2
Content-Type: application/json